apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    namespace: default
    app: mongodb
spec:
  template:
    metadata:
      labels:
        app: mongodb
        version: v1
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
