apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-single
  labels:
    namespace: default
    app: node-single
spec:
  template:
    metadata:
      labels:
        app: node-single
        version: v1
    spec:
      restartPolicy: Always
      containers:
      - name: node-single
        image: 128.110.154.205:5000/node-single-test
        ports:
        - containerPort: 14000
        env:
        - name: FUNC_TYPE
          value: compute
        - name: NUM_PROCS
          value: "4"
        - name: USE_CG_TRICK
          value: "0"
        - name: V8_CPU_TIME
          value: "0.65"
        - name: UV_CPU_TIME
          value: "0.35"
        - name: ERROR_RATE
          value: "0"
        - name: NODE_CLUSTER_SCHED_POLICY
          value: rr
        resources:
          limits:
            cpu: 6000m
          requests:
            cpu: 6000m
        securityContext:
          privileged: true
