apiVersion: v1
kind: Service
metadata:
  name: node-envoy
  labels:
    app: node-envoy
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 14000
    targetPort: http
    protocol: TCP
  selector:
    app: node-envoy
