apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-compute
  labels:
    namespace: default
    app: node-compute
spec:
  template:
    metadata:
      labels:
        app: node-compute
        version: v1
    spec:
      containers:
      - name: node-compute
        image:
        ports:
        - containerPort: 15000

