apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-single-envoy
  labels:
    app: node-single-envoy
spec:
  selector:
    matchLabels:
      app: node-single-envoy
  template:
    metadata:
      labels:
        app: node-single-envoy
    spec:
      containers:
      - name: node-single-envoy
        image: 128.110.154.168:5000/faas-envoy
        imagePullPolicy: Always
        env:
        - name: "ENVOY_LB_ALG"
          value: "ROUND_ROBIN"
        - name: "SERVICE_NAME"
          value: "node-single-headless"
        ports:
        - name: http
          containerPort: 14000
        - name: envoy-admin
          containerPort: 9901
