apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-test
  labels:
    namespace: default
    app: python-test
spec:
  template:
    metadata:
      labels:
        app: python-test
        version: v1
    spec:
      containers:
      - name: python-redis
        image: 128.110.154.115:5000/python-test
        ports:
        - containerPort: 15000
        env:
        - name: FUNC_TYPE
          value: "redis"
        - name: FLASK_MODE
          value: "single"
