apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python
  labels:
    namespace: default
    app: python
spec:
  template:
    metadata:
      labels:
        app: python
        version: v1
    spec:
      containers:
      - name: python-redis
        image: 128.110.154.205:5000/python-test
        ports:
        - containerPort: 14000
        env:
        - name: FUNC_TYPE
          value: compute
        - name: FLASK_MODE
          value: multiprocess
        - name: NUMPROCS
          value: "12"
        - name: ERROR_RATE
          value: "0"
        resources:
          requests:
            cpu: "3000m"
            memory: "256Mi"
          limits:
            cpu: "3000m"
            memory: "256Mi"
