apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python
  labels:
    namespace: default
    app: python
spec:
  template:
    metadata:
      labels:
        app: python
        version: v1
    spec:
      containers:
      - name: python-redis
        image: 128.110.154.168:5000/python-test
        ports:
        - containerPort: 14000
        env:
        - name: FUNC_TYPE
          value: redis
        - name: FLASK_MODE
          value: single
        - name: ERROR_RATE
          value: "0"
