kind: Service
apiVersion: v1
metadata:
  name: python
  labels:
    app: python
    service: python
spec:
  selector:
    app: python
  ports:
  #- protocol: TCP
  - port: 14000
    name: http
  type: LoadBalancer
