kind: Service
apiVersion: v1
metadata:
  name: python-test
  labels:
    app: python-test
    service: python-test
spec:
  selector:
    app: python-test
  ports:
  #- protocol: TCP
  - port: 14000
    name: http
  type: LoadBalancer
