
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-single-test
  labels:
    namespace: default
    app: node-single-test
spec:
  template:
    metadata:
      labels:
        app: node-single-test
        version: v1
    spec:
      restartPolicy: Always
      containers:
      - name: node-single-compute
        image: 128.110.154.168:5000/node-single-test
        ports:
        - containerPort: 14000
        env:
        - name: FUNC_TYPE
          value: "redis"
        - name: NUM_PROCS
          value: "1"
        - name: USE_CG_TRICK
          value: "0"
        - name: V8_CPU_TIME
          value: "0.65"
        - name: UV_CPU_TIME
          value: "0.35"
        - name: ERROR_RATE
          value: "-4"
        resources:
          limits:
            cpu: "250m"
        securityContext:
          privileged: true
