kind: Service
apiVersion: v1
metadata:
  name: node-single
  labels:
    app: node-single
    service: node-single
spec:
  selector:
    app: node-single
  ports:
  #- protocol: TCP
  - port: 14000
    name: http
  type: LoadBalancer

