apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: python-test
spec:
  host: python-test #.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
